const mapDirections=(origin,destination,mode='transit')=>`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&travelmode=${mode}`;
const search=place=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`;
const L=(label,url)=>({label,url});
const M=(time,title,text,label,url,credit='')=>({time,title,text,label,url,credit});
const P=(name,coord,image,url,desc)=>({name,coord,image,url,desc});
const days=[
 {date:'FRI 2',number:'02',city:'ARRIVAL',subtitle:'Check in · Taiwanese dinner · first drinks',title:'Land, eat, settle in',image:'skyline',lead:'Reach the Guting area, drop bags, then let the first night be about dinner and one good bar. A nine-person queue after a flight is optional, not mandatory.',primary:'Shin Yeh is the reserve-a-table fallback for all nine. Try Din Tai Fung Xinsheng only if the queue is short enough.',backup:'If dinner runs late, go straight to the booked table and save dumplings for Saturday lunch.',center:[121.528,25.034],zoom:13.1,pitch:55,bearing:-16,weather:'Oct 2',moments:[
 M('LATE PM','Airport → Guting area','Two prebooked vans or a minibus take the whole group and luggage to the neighborhood. Enter the exact drop-off privately with the driver.','Transfer guide','https://www.tripool.app/en/articles/airport-transfer-guide'),
 M('DINNER','Din Tai Fung Xinsheng, if practical','Mr K’s opening-night pick. Use the dine-in Xinsheng branch near Dongmen, not the original Xinyi Road takeaway shop. Large groups may need to split into tables; queue intake can close early.','Official branches','https://www.dintaifung.com.tw/store.php','Mr K'),
 M('BACKUP','Shin Yeh Zhongxiao','Book a nine-person Taiwanese dinner in advance. It has a large dining room and private rooms, and is closer to the evening bars.','Reserve a table','https://www.tablecheck.com/zh-TW/shin-yeh-zhongxiao-store/reserve/landing','Mr S'),
 M('LATE','Draft Land or The Public House','Draft Land Zhongxiao is the easier drop-in choice. The Public House is a more intimate cocktail stop: contact it first for a party of nine.','Draft Land','https://www.draftland.tw/tpe','Mr K + Mr S')],
 links:[L('To Xinsheng',mapDirections('Guting Station, Taipei','Din Tai Fung Xinsheng Branch, Taipei')),L('To Shin Yeh',mapDirections('Guting Station, Taipei','Shin Yeh Taiwanese Cuisine Zhongxiao Branch, Taipei')),L('Bar walking route',mapDirections('Shin Yeh Zhongxiao Branch, Taipei','Draft Land Zhongxiao, Taipei','walking'))],
 move:'Guting → Dongmen: Orange line one stop, then follow Exit 6 and walk to Xinsheng. For Shin Yeh, take the Blue line to Zhongxiao Dunhua after changing at Zhongxiao Xinsheng, or use three taxis. Draft Land Zhongxiao is a short walk from the Zhongxiao dining area.',
 pins:[P('Guting area · approximate base',[121.5225,25.026], 'memorial',search('Guting Station Taipei'),'Public station marker; the accommodation is somewhere nearby.'),P('Din Tai Fung Xinsheng',[121.5301,25.0332],'memorial','https://www.dintaifung.com.tw/store.php','Dine-in dumplings; queue may be long.'),P('Shin Yeh Zhongxiao',[121.5481,25.0416],'skyline','https://www.shinyeh.com.tw/content/en/brand/Store.aspx?BrandId=1&Id=4','Reservable Taiwanese dinner for the group.'),P('Draft Land Zhongxiao',[121.5539,25.0398],'skyline','https://www.draftland.tw/tpe','Cocktails on tap, close to dinner.')]
 },
 {date:'SAT 3',number:'03',city:'CITY',subtitle:'Soy milk · old Taipei · skyline · night market',title:'Taste the city',image:'nightmarket',lead:'Start with a classic breakfast, cross the civic heart of Taipei, then choose a short skyline walk or indoor play before the night market. This is the fullest city day.',primary:'Fu Hang line and Xiangshan steps are optional. The group can split and meet for lunch or the market.',backup:'Rain plan: Huashan 1914 shops, indoor archery or the National Palace Museum. Skip the exposed Xiangshan steps in a storm.',center:[121.545,25.040],zoom:11.7,pitch:50,bearing:12,weather:'Oct 3',moments:[
 M('EARLY','Fu Hang Soy Milk','Mr K and Mr S both chose this. Arrive early for the renowned thick bread, eggs and soy milk. If the queue is huge, grab breakfast near Guting and join the group at Huashan.','Fu Hang guide','https://www.travel.taipei/en/pictorial/article/48481','Mr K + Mr S'),
 M('MID AM','Coffee + Huashan 1914','Walk about 10 minutes to creative shops and cafés. Simple Kaffa opens at 10; a group of nine may order and sit separately.','Huashan shops','https://www.huashan1914.com/en-US/store','Mr K'),
 M('NOON','Chiang Kai-shek Memorial Hall','MRT or a short car ride to the huge square and park. Browse at your own pace; find lunch nearby or move Din Tai Fung here if Friday’s queue won.','Location',search('Chiang Kai-shek Memorial Hall Taipei'),'Mr S'),
 M('AFTERNOON','Xiangshan or indoor archery','The Xiangshan trail has steep steps but a classic city view. If it is hot or wet, book beginner-friendly indoor archery at ArcheryBase instead. Both are Mr S ideas.','ArcheryBase bookings','https://archerybase.tw/','Mr S'),
 M('SUNSET','Xinyi design stroll','Browse the fashion pop-up along Xinyi’s Xiangti Avenue during Taipei Fashion Week through 4 October. Treat it as a flexible pass-through, not a ticketed show.','Event details','https://www.travel.taipei/en/event-calendar/details/66796'),
 M('DINNER','Raohe Night Market','Mr K’s market pick; Songshan MRT is directly on the Green line back toward Guting. Pepper buns and smaller stall dishes make it easy to split and regroup. Ningxia is the alternative.','Raohe guide','https://travel.taipei/en/attraction/details/1691','Mr K + Mr S')],
 links:[L('To Fu Hang',mapDirections('Guting Station, Taipei','Fu Hang Soy Milk, Taipei')),L('To memorial',mapDirections('Huashan 1914 Creative Park','Chiang Kai-shek Memorial Hall, Taipei','walking')),L('To Xiangshan',mapDirections('Chiang Kai-shek Memorial Hall, Taipei','Xiangshan Trailhead, Taipei')),L('To Raohe',mapDirections('Taipei 101, Taipei','Raohe Street Night Market, Taipei'))],
 move:'Guting → Fu Hang: Orange line to Zhongxiao Xinsheng, then Blue line one stop west to Shandao Temple; for nine people, three taxis may be simpler early in the morning. Fu Hang → Huashan is walkable. From Xinyi to Raohe, use three short taxis for the group. By MRT, take Red to Da’an, Brown to Nanjing Fuxing, then Green to Songshan. Raohe → Guting is a direct Green line from Songshan.',
 pins:[P('Fu Hang Soy Milk',[121.5247,25.0443],'memorial','https://www.travel.taipei/en/pictorial/article/48481','Breakfast icon with a line; get there early.'),P('Huashan 1914',[121.5296,25.0442],'memorial','https://www.huashan1914.com/en-US/store','Coffee, design shops and rain cover.'),P('Memorial Hall',[121.5199,25.0347],'memorial',search('Chiang Kai-shek Memorial Hall Taipei'),'Open square and civic landmark.'),P('Xiangshan',[121.5702,25.0263],'skyline',search('Xiangshan Trail Taipei'),'Steep steps, city panorama; avoid lightning.'),P('Raohe Night Market',[121.5773,25.0502],'nightmarket','https://travel.taipei/en/attraction/details/1691','A street-food dinner by Songshan Station.')]
 },
 {date:'SUN 4',number:'04',city:'NATURE',subtitle:'Soy milk · grassland · massage · craft beer',title:'Out to the grassland',image:'grassland',lead:'The big nature day is the Qingtiangang grassland in Yangmingshan. Return to Taipei for a massage and a long dinner at Taihu Da’an. Make the mountain call after checking the morning sky.',primary:'Qingtiangang’s main circular path is roughly 2.4 km and about an hour when open. Enjoy the grassy viewpoint without committing to a longer hike.',backup:'If the park warns of storms, fog or closures, switch to National Palace Museum (open Sunday 09:00–17:00), then massage and Taihu as planned.',center:[121.5746,25.1659],zoom:12.4,pitch:60,bearing:-25,weather:'Oct 4',moments:[
 M('BREAKFAST','Yong He Soy Milk King','Mr K’s Sunday breakfast pick. A quick local breakfast before leaving the city; confirm the exact branch and hours in Maps as similar names exist.','Find branch',search('Yong He Soy Milk King Fuxing South Road Taipei'),'Mr K'),
 M('MORNING','Charter to Qingtiangang','Book two cars or a minibus with return pickup. Leave before the late-morning traffic; the road can be slow on weekends. Bring a light shell, water and shoes with grip.','Charter comparison','https://www.klook.com/en-SG/activity/16320-yangmingshan-private-car-charter-taipei/','Mr K + Mr S'),
 M('MIDDAY','Grassland loop or shorter stroll','Follow marked park paths. Keep distance from water buffalo. Skip the exposed trail in thunder, thick fog or rain; check same-day park notices. Longer Qixing Mountain is a separate, harder hike and only for a well-equipped subgroup.','Park trail grades','https://www.ymsnp.gov.tw/en/sglarticle/trail-classification-system','Mr K + Mr S'),
 M('RAIN PLAN','National Palace Museum','The strongest indoor substitute, with major Chinese art collections and enough space to split into smaller groups. It is closed Monday, so Sunday is the day to use it.','Museum hours','https://www.npm.gov.tw/Articles.aspx?l=2&sno=02007001','Mr S'),
 M('AFTERNOON','Massage back in Taipei','Request nine overlapping sessions at 6 Star Massage, or split the group into two nearby time slots. Reservation requests need confirmation.','Request slots','https://www.footmassage.com.tw/reserve.html','Mr K'),
 M('EVENING','Taihu Da’an','Book a long drinks-and-dinner table. Craft beer and substantial food make this a good regrouping point after separate afternoon choices.','Reserve Taihu','https://www.opentable.com.tw/restaurant/profile/181709','Mr K')],
 links:[L('Drive to grassland',mapDirections('Guting Station, Taipei','Qingtiangang Visitor Center, Taipei','driving')),L('Public bus option','https://www.ymsnp.gov.tw/en/listicle/faq/756'),L('Museum fallback',mapDirections('Guting Station, Taipei','National Palace Museum Taipei')),L('To Taihu',mapDirections('Guting Station, Taipei','Taihu Brewing Da’an, Taipei'))],
 move:'Private charter is easiest for nine. Ask for two vehicles or a licensed minibus, a two- to three-hour park stop, and an agreed return pickup. Public route: MRT to Jiantan or Shilin, then R15/S15 bus toward Qingtiangang; weekend buses can be crowded. Back in town, use MRT or three taxis between massage and Taihu.',
 pins:[P('Yong He Soy Milk King · branch search',[121.5436,25.032],'memorial',search('Yong He Soy Milk King Fuxing South Road Taipei'),'Confirm the location before setting out.'),P('Qingtiangang Grassland',[121.5746,25.1659],'grassland','https://www.ymsnp.gov.tw/en/sglarticle/trail-classification-system','Open views, water buffalo and changeable mountain weather.'),P('National Palace Museum',[121.5485,25.1023],'museum','https://www.npm.gov.tw/Articles.aspx?l=2&sno=02007001','Sunday indoor fallback.'),P('Taihu Da’an',[121.5449,25.0387],'skyline','https://www.taihubrewing.com/en/pages/taihu-retail','Book the nine-person dinner.')]
 },
 {date:'MON 5',number:'05',city:'DEPARTURE',subtitle:'Old-town stroll · lunch · airport',title:'One last Taipei morning',image:'memorial',lead:'Keep the final day close to the city, with a simple morning choice and an early lunch. Leave plenty of room for luggage pickup and the airport transfer.',primary:'Choose Longshan Temple and one short old-town wander, or just café time near Guting if the weekend has been full.',backup:'Rain plan: indoor coffee and lunch near the base; skip the extra cross-town stop.',center:[121.507,25.037],zoom:12.8,pitch:50,bearing:0,weather:'Oct 5',moments:[
 M('MORNING','Longshan Temple + Bopiliao','Mr S’s final cultural stop. Go by Orange/Blue MRT or taxi, then walk the historic lanes. Dress respectfully and keep the visit short if the group wants a slower morning.','Temple location',search('Longshan Temple Taipei'),'Mr S'),
 M('OPTION','Ximending streets','A colorful urban contrast nearby, with shops and snacks. Choose this only if luggage is packed and everyone has energy.','Walking route',mapDirections('Longshan Temple, Taipei','Ximending, Taipei','walking'),'Mr S'),
 M('LUNCH','A final Taiwanese meal','Pick somewhere near Guting or Taipei Main so the transfer stays easy. Jin Feng is closed on Mondays according to current listings, so don’t build the departure lunch around it. Din Tai Fung Xinsheng is an alternative if the queue permits.','Din Tai Fung branches','https://www.dintaifung.com.tw/store.php','Mr S'),
 M('EARLY PM','Collect bags → Taoyuan Airport','Meet the prebooked vehicles in the Guting area around midday. Allow for traffic, bag drop and security. Confirm your actual check-in cutoff from the airline itinerary privately.','Airport transfer guide','https://www.tripool.app/en/articles/airport-transfer-guide')],
 links:[L('To Longshan',mapDirections('Guting Station, Taipei','Longshan Temple, Taipei')),L('Back to Guting',mapDirections('Ximending, Taipei','Guting Station, Taipei')),L('Airport Express','https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable-A1')],
 move:'Guting → Longshan Temple: Orange line to Dongmen, then Blue line from Zhongxiao Xinsheng to Longshan Temple, or take three taxis for the group. Return to Guting by MRT or car before collecting bags. If using Airport Express, reach Taipei Main Station, take the express train, and follow the airport terminal signs.',
 pins:[P('Longshan Temple',[121.4998,25.0372],'memorial',search('Longshan Temple Taipei'),'Historic morning stop.'),P('Ximending',[121.5064,25.0422],'skyline',search('Ximending Taipei'),'Optional colorful street wander.'),P('Guting area · approximate base',[121.5225,25.026],'memorial',search('Guting Station Taipei'),'Return for bags before the airport.')]
 }
];
const foods=[
 ['01','BREAKFAST','Fu Hang Soy Milk','A celebrated local breakfast; expect a queue. Early start or split the group. Mr K + Mr S.','https://www.travel.taipei/en/pictorial/article/48481','Fallback: breakfast around Guting; meet at Huashan later.'],
 ['02','FRIDAY DINNER','Din Tai Fung Xinsheng','Mr K pick. Dine-in branch near Dongmen; original Xinyi Road branch is takeaway only. Nine may be split.','https://www.dintaifung.com.tw/store.php','Bookable fallback: Shin Yeh Zhongxiao, Taiwanese banquet food.'],
 ['03','RESERVABLE TABLE','Shin Yeh Zhongxiao','Taiwanese family-style dinner; large room and private dining. Mr S option that works for nine.','https://www.tablecheck.com/zh-TW/shin-yeh-zhongxiao-store/reserve/landing','Ask for one table or adjacent tables, not a walk-in.'],
 ['04','SUNDAY BREAKFAST','Yong He Soy Milk King','Mr K pick for savory soy milk, rice rolls and egg pancakes. Verify the specific Fuxing South Road branch before leaving.','https://www.google.com/maps/search/?api=1&query=Yong+He+Soy+Milk+King+Fuxing+South+Road+Taipei','Fallback: a Guting breakfast shop on your street.'],
 ['05','NIGHT MARKET','Raohe Street Market','Pepper buns, skewers and sweets; right by Songshan Green line. Mr K + Mr S.','https://travel.taipei/en/attraction/details/1691','Fallback: Ningxia Market, also convenient from Guting via Zhongshan.'],
 ['06','COCKTAILS','Draft Land / The Public House','Mr K’s Friday bar ideas. Draft Land works better as a flexible drop-in; contact The Public House for nine.','https://www.draftland.tw/tpe','If both fill: Taihu Da’an or another larger brewpub.'],
 ['07','CRAFT BEER + DINNER','Taihu Da’an','Mr K’s Sunday night anchor. Reserve a group table; pub food can satisfy different appetites.','https://www.opentable.com.tw/restaurant/profile/181709','Fallback: Shin Yeh Zhongxiao for a table, or small-group market dinner.'],
 ['08','EXTRA OPTIONS','Meat Boss / Wang’s Braised Pork Rice','Mr S’s Friday alternatives. Meat Boss needs a booking inquiry for nine; Wang’s is a simpler local meal if the group can split.','https://www.google.com/maps/search/?api=1&query=Meat+Boss+Taipei','Confirm branch, hours and capacity before going.']
];
const photo=name=>`./assets/${name}.jpg`;
let selected=0, map=null, markers=[],popup=null;
function dayMarkup(d,i){return `<button class="day-item ${selected===i?'active':''}" data-day="${i}" type="button" aria-label="Show ${d.date} ${d.title}"><span class="day-date">OCT<strong>${d.number}</strong></span><span class="day-text"><small>${d.date} · ${d.city}</small><b>${d.title}</b><span>${d.subtitle}</span></span><span class="day-arrow">›</span></button>`}
function renderDays(){document.getElementById('dayList').innerHTML=days.map(dayMarkup).join('');document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>selectDay(+b.dataset.day)))}
function renderFood(){document.getElementById('foodList').innerHTML=foods.map(f=>`<article class="booking-card"><div class="booking-index">${f[0]} <span>${f[1]}</span></div><h3>${f[2]}</h3><p>${f[3]}</p><a href="${f[4]}" target="_blank" rel="noopener">Open venue ↗</a><div class="booking-alt">${f[5]}</div></article>`).join('')}
function renderDetail(){const d=days[selected];document.getElementById('detailContent').innerHTML=`<div class="detail-hero"><img src="${photo(d.image)}" alt="Illustrative Taipei scene"><span class="detail-hero-label">${d.city} · OCTOBER 2026</span><span class="detail-number">${d.number}</span></div><div class="detail-inner"><div class="detail-overline"><span>${d.date} OCTOBER</span><span>DAY ${selected+1} OF 4</span></div><h2>${d.title}</h2><p class="detail-lead">${d.lead}</p><div class="pace"><div><small>MAIN IDEA</small><p>${d.primary}</p></div><div><small>FLEX OPTION</small><p>${d.backup}</p></div></div><div id="dayWeather" class="choice-note">Forecast loading…</div><div class="section-label">THE SIMPLE PLAN</div><div class="timeline">${d.moments.map(m=>`<div class="moment"><span class="moment-dot"></span><div><h3><time>${m.time}</time>${m.title}${m.credit?`<span class="credit-chip">· ${m.credit}</span>`:''}</h3><p>${m.text}</p>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">${m.label} ↗</a>`:''}</div></div>`).join('')}</div><div class="section-label">OPEN & GO</div><div class="detail-links">${d.links.map(l=>`<a href="${l.url}" target="_blank" rel="noopener">${l.label} ↗</a>`).join('')}</div><div class="detail-bottom"><strong>Getting around</strong><br>${d.move}<br><br><strong>Map note</strong><br>The line joins places visually; use the directions above for actual streets, vehicles and traffic.</div><div class="more-days"><button id="prevDay" type="button" ${selected===0?'disabled':''}>← Previous</button><button id="nextDay" type="button" ${selected===3?'disabled':''}>Next →</button></div></div>`;document.getElementById('prevDay').addEventListener('click',()=>selectDay(selected-1));document.getElementById('nextDay').addEventListener('click',()=>selectDay(selected+1));updateDayWeather()}
function selectDay(i){if(i<0||i>=days.length)return;selected=i;renderDays();renderDetail();const d=days[i];document.getElementById('mapCaption').textContent=d.title;document.querySelectorAll('.place').forEach(b=>b.classList.toggle('active',b.dataset.place===({ARRIVAL:'guting',CITY:'east',NATURE:'mountain',DEPARTURE:'central'}[d.city])));if(map){map.flyTo({center:d.center,zoom:d.zoom,pitch:d.pitch,bearing:d.bearing,duration:1100,essential:true});setMarkers(d.pins,d.city)}if(window.innerWidth<700)document.querySelector('.detail').scrollIntoView({behavior:'smooth',block:'start'});else document.querySelector('.detail').scrollTop=0}
function switchTab(tab){document.querySelectorAll('.tab').forEach(b=>{let yes=b.dataset.tab===tab;b.classList.toggle('active',yes);b.setAttribute('aria-selected',yes?'true':'false')});document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===tab+'-panel'));if(window.innerWidth<700&&tab!=='days')document.querySelector('.sidebar').scrollIntoView({behavior:'smooth',block:'start'})}
function setMarkers(pins,city){markers.forEach(m=>m.remove());markers=[];if(popup){popup.remove();popup=null}pins.forEach((p,i)=>{let e=document.createElement('button');e.type='button';e.className='map-pin '+(city==='NATURE'?'nature':'');e.textContent=String(i+1);e.setAttribute('aria-label',`Explore ${p.name}`);e.addEventListener('click',()=>{if(popup)popup.remove();popup=new maplibregl.Popup({offset:20,maxWidth:'260px'}).setLngLat(p.coord).setHTML(`<div class="pin-popup"><img src="${photo(p.image)}" alt=""><div><small>${city}</small><h3>${p.name}</h3><p>${p.desc}</p><a href="${p.url}" target="_blank" rel="noopener">Open details ↗</a></div></div>`).addTo(map)});markers.push(new maplibregl.Marker({element:e,anchor:'bottom'}).setLngLat(p.coord).addTo(map))})}
function showOverview(){document.getElementById('mapCaption').textContent='The entire weekend';document.querySelectorAll('.place').forEach(b=>b.classList.toggle('active',b.dataset.place==='all'));if(map){map.fitBounds([[121.17,24.98],[121.67,25.20]],{padding:Math.min(68,window.innerWidth*.07),pitch:35,bearing:0,duration:1000,essential:true});setMarkers([P('Taoyuan Airport',[121.232,25.078],'skyline','https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable-A1','Arrival and departure gateway; no flight details shown.'),P('Guting · approximate base',[121.5225,25.026],'memorial',search('Guting Station Taipei'),'Public area marker only.'),P('Central Taipei',[121.5247,25.0443],'memorial','https://www.huashan1914.com/en-US/store','Breakfast, coffee and the memorial.'),P('East Taipei',[121.564,25.041],'skyline','https://www.travel.taipei/en/event-calendar/details/66796','Skyline, food and evening markets.'),P('Qingtiangang',[121.5746,25.1659],'grassland','https://www.ymsnp.gov.tw/en/sglarticle/trail-classification-system','Weather-dependent nature day.')],'TRIP STOP')}}
function focusPlace(place){if(place==='all')return showOverview();if(place==='airport'){document.getElementById('mapCaption').textContent='Taoyuan Airport';document.querySelectorAll('.place').forEach(b=>b.classList.toggle('active',b.dataset.place==='airport'));map?.flyTo({center:[121.232,25.078],zoom:12,pitch:48,bearing:0,duration:1000,essential:true});if(map)setMarkers([P('Taoyuan Airport',[121.232,25.078],'skyline','https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable-A1','Arrival and departure gateway.')],'AIRPORT');return}if(place==='guting')return selectDay(0);if(place==='central')return selectDay(3);if(place==='east')return selectDay(1);if(place==='mountain')return selectDay(2)}
function initMap(){if(!window.maplibregl){document.getElementById('mapError').hidden=false;return}try{map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/bright',center:[121.53,25.08],zoom:10,pitch:35,bearing:0,projection:{type:'globe'},canvasContextAttributes:{antialias:true},attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:true,showZoom:true,visualizePitch:true}),'bottom-right');map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');map.on('load',()=>{const route=[[121.232,25.078],[121.445,25.055],[121.5225,25.026],[121.5301,25.0332],[121.5539,25.0398],[121.5247,25.0443],[121.5199,25.0347],[121.5702,25.0263],[121.5773,25.0502],[121.5225,25.026],[121.5746,25.1659],[121.5449,25.0387],[121.4998,25.0372],[121.5225,25.026],[121.232,25.078]];map.addSource('trip-route',{type:'geojson',data:{type:'Feature',geometry:{type:'LineString',coordinates:route}}});map.addLayer({id:'route-halo',type:'line',source:'trip-route',paint:{'line-color':'#ffffff','line-width':7,'line-opacity':.78}});map.addLayer({id:'route-line',type:'line',source:'trip-route',paint:{'line-color':'#e4784a','line-width':3,'line-opacity':.95,'line-dasharray':[2,1]}});try{const layers=map.getStyle().layers;const first=layers.find(l=>l.type==='symbol'&&l.layout&&l.layout['text-field']);if(!map.getSource('building-data'))map.addSource('building-data',{url:'https://tiles.openfreemap.org/planet',type:'vector'});map.addLayer({id:'trip-3d-buildings',source:'building-data','source-layer':'building',type:'fill-extrusion',minzoom:15,paint:{'fill-extrusion-color':'#8daead','fill-extrusion-opacity':.68,'fill-extrusion-height':['interpolate',['linear'],['zoom'],15,0,16,['coalesce',['get','render_height'],10]],'fill-extrusion-base':0}},first?.id)}catch(e){console.warn('3D buildings unavailable',e)}showOverview()});map.on('error',e=>{const message=String(e.error?.message||'');if(/Failed to fetch|NetworkError|tile/i.test(message))document.getElementById('mapError').hidden=false})}catch(e){document.getElementById('mapError').hidden=false}}
let forecast=null,forecastStamp='';const weatherWords={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',80:'Showers',81:'Showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm',99:'Thunderstorm'};
function getWeatherFor(i,area='city'){const d=forecast?.[area]?.daily;if(!d)return null;const idx=d.time.indexOf(`2026-10-0${i+2}`);if(idx<0)return null;return {hi:Math.round(d.temperature_2m_max[idx]),lo:Math.round(d.temperature_2m_min[idx]),rain:d.precipitation_probability_max[idx],code:d.weather_code[idx]}}
function updateDayWeather(){const el=document.getElementById('dayWeather');if(!el)return;const w=getWeatherFor(selected,selected===2?'mountain':'city');el.innerHTML=w?`<strong>${selected===2?'Grassland':'Taipei'} forecast:</strong> ${weatherWords[w.code]||'Mixed conditions'}, ${w.lo}–${w.hi}°C · ${w.rain}% maximum daily rain chance. <a href="#" id="weatherOpen">See all days ↗</a>`:'<strong>Weather:</strong> Check live Taipei conditions before heading out. <a href="https://www.cwa.gov.tw/V8/E/" target="_blank" rel="noopener">Official forecast ↗</a>';document.getElementById('weatherOpen')?.addEventListener('click',e=>{e.preventDefault();switchTab('weather')})}
function renderWeather(){let target=document.getElementById('weatherList');target.innerHTML=days.map((d,i)=>{const city=getWeatherFor(i), mountain=i===2?getWeatherFor(i,'mountain'):null;return `<article class="weather-card"><header><span>${d.date} OCT · ${i===2?'GRASSLAND':'TAIPEI'}</span><strong>${(mountain||city)?.hi??'–'}°</strong></header><p>${mountain||city?`${weatherWords[(mountain||city).code]||'Mixed conditions'} · low ${(mountain||city).lo}°C · rain chance up to ${(mountain||city).rain}%`:'Live forecast unavailable; use official weather link below.'}</p>${mountain&&city?`<small>City: ${city.lo}–${city.hi}°C · ${city.rain}% rain chance</small>`:''}</article>`}).join('')+`<p class="small-note">${forecastStamp?`Updated ${forecastStamp} (Taipei time).`:'Live forecast unavailable.'} Probability is the maximum daily value from the forecast, not a guarantee of rain at every stop.</p>`}
async function loadWeather(){const daily='temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code';const mk=(lat,lon)=>`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=${daily}&timezone=Asia%2FTaipei&forecast_days=7`;try{const [c,m]=await Promise.all([fetch(mk(25.033,121.565)),fetch(mk(25.166,121.575))]);if(!c.ok||!m.ok)throw Error('weather unavailable');forecast={city:await c.json(),mountain:await m.json()};forecastStamp=new Intl.DateTimeFormat('en-SG',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Taipei'}).format(new Date())}catch(e){forecast=null}renderWeather();updateDayWeather()}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));document.querySelectorAll('.place').forEach(b=>b.addEventListener('click',()=>focusPlace(b.dataset.place)));document.getElementById('overviewBtn').addEventListener('click',showOverview);document.getElementById('resetNorthBtn').addEventListener('click',()=>map?.easeTo({bearing:0,pitch:35,duration:700}));document.getElementById('printBtn').addEventListener('click',()=>window.print());renderDays();renderFood();renderDetail();initMap();loadWeather();
